import type { DormRecord } from "./dorms-types";

const OEJAB = "https://www.oejab.at/studierende-jugend/studierendenwohnheime";
const WIST = "https://www.wist.at/";
const HOME4STUDENTS = "https://home4students.at/";
const WIHAST = "https://www.wihast.at/";

const VIENNA_DORMS: DormRecord[] = [
  {
    id: "dorm-wien-johannesgasse",
    name: "ÖJAB-Haus Johannesgasse",
    address: "Johannesgasse 8",
    postcode: "1010",
    city: "Wien",
    lat: 48.2038,
    lng: 16.3789,
    priceFrom: 320,
    priceTo: 520,
    rooms: 1,
    url: OEJAB,
    provider: "ÖJAB",
    note: "Central 1st district — close to Uni Wien.",
  },
  {
    id: "dorm-wien-wihast",
    name: "WIHAST Hirschengasse",
    address: "Hirschengasse 23",
    postcode: "1060",
    city: "Wien",
    lat: 48.1985,
    lng: 16.3522,
    priceFrom: 280,
    priceTo: 450,
    rooms: 1,
    url: WIHAST,
    provider: "WIHAST",
    note: "Worker-student housing near Mariahilf / TU area.",
  },
  {
    id: "dorm-wien-tendler",
    name: "WIHAST Tendlergasse",
    address: "Tendlergasse 12",
    postcode: "1090",
    city: "Wien",
    lat: 48.2265,
    lng: 16.3568,
    priceFrom: 290,
    priceTo: 460,
    rooms: 1,
    url: WIHAST,
    provider: "WIHAST",
    note: "Near Alsergrund campuses and AKH.",
  },
  {
    id: "dorm-wien-burgerspital",
    name: "ÖJAB-Haus Burgenland",
    address: "Bürgerspitalgasse 19",
    postcode: "1060",
    city: "Wien",
    lat: 48.1968,
    lng: 16.3485,
    priceFrom: 300,
    priceTo: 480,
    rooms: 1,
    url: OEJAB,
    provider: "ÖJAB",
    note: "Mariahilf location with good U-Bahn links.",
  },
  {
    id: "dorm-wien-europahaus",
    name: "ÖJAB-Europahaus Dr. Bruno Buchwieser",
    address: "Linzer Straße 429",
    postcode: "1140",
    city: "Wien",
    lat: 48.1982,
    lng: 16.2654,
    priceFrom: 260,
    priceTo: 420,
    rooms: 1,
    url: OEJAB,
    provider: "ÖJAB",
    note: "Large residence in Penzing — fitness & sauna on site.",
  },
  {
    id: "dorm-wien-seestadt",
    name: "ÖJAB-Haus Seestadt Aspern",
    address: "Sonnenallee 41",
    postcode: "1220",
    city: "Wien",
    lat: 48.2275,
    lng: 16.4855,
    priceFrom: 250,
    priceTo: 390,
    rooms: 1,
    url: OEJAB,
    provider: "ÖJAB",
    note: "Modern Aspern Seestadt campus — U2 connection.",
  },
  {
    id: "dorm-wien-donaufeld",
    name: "ÖJAB-Haus Donaufeld",
    address: "Donaufelder Straße 54",
    postcode: "1210",
    city: "Wien",
    lat: 48.2485,
    lng: 16.4422,
    priceFrom: 270,
    priceTo: 410,
    rooms: 1,
    url: OEJAB,
    provider: "ÖJAB",
    note: "Floridsdorf — affordable rooms north of the Danube.",
  },
  {
    id: "dorm-wien-pfeilgasse",
    name: "Akademikerhilfe Pfeilgasse",
    address: "Pfeilgasse 3a",
    postcode: "1080",
    city: "Wien",
    lat: 48.2115,
    lng: 16.3488,
    priceFrom: 310,
    priceTo: 490,
    rooms: 1,
    url: "https://www.akademikerhilfe.at/",
    provider: "Akademikerhilfe",
    note: "Josefstadt — walking distance to Uni Wien main building.",
  },
  {
    id: "dorm-wien-home4students",
    name: "home4students Wien",
    address: "Sensengasse 2b/1",
    postcode: "1090",
    city: "Wien",
    lat: 48.2248,
    lng: 16.3512,
    priceFrom: 350,
    priceTo: 580,
    rooms: 1,
    url: HOME4STUDENTS,
    provider: "home4students",
    note: "Operator hub for multiple Vienna student residences.",
  },
];

const GRAZ_DORMS: DormRecord[] = [
  {
    id: "dorm-graz-oejab-glacis",
    name: "ÖJAB-Haus Graz",
    address: "Glacisstraße 39–41",
    postcode: "8010",
    city: "Graz",
    lat: 47.0742,
    lng: 15.4418,
    priceFrom: 280,
    priceTo: 430,
    rooms: 1,
    url: OEJAB,
    provider: "ÖJAB",
    note: "Near Kunstuniversität and old town.",
  },
  {
    id: "dorm-graz-oejab-steiermark",
    name: "ÖJAB-Haus Steiermark",
    address: "Liebiggasse 4",
    postcode: "8010",
    city: "Graz",
    lat: 47.0718,
    lng: 15.4495,
    priceFrom: 290,
    priceTo: 440,
    rooms: 1,
    url: OEJAB,
    provider: "ÖJAB",
    note: "Close to TU Graz and Uni Graz.",
  },
  {
    id: "dorm-graz-wist-moserhof",
    name: "WIST Moserhofgasse",
    address: "Moserhofgasse 34",
    postcode: "8010",
    city: "Graz",
    lat: 47.0685,
    lng: 15.4542,
    priceFrom: 300,
    priceTo: 460,
    rooms: 1,
    url: WIST,
    provider: "WIST Steiermark",
    note: "Classic WIST residence near campus district.",
  },
  {
    id: "dorm-graz-khg",
    name: "KHG Studierendenheim Leechgasse",
    address: "Leechgasse 24",
    postcode: "8010",
    city: "Graz",
    lat: 47.0785,
    lng: 15.4468,
    priceFrom: 270,
    priceTo: 400,
    rooms: 1,
    url: "https://www.khg-graz.at/",
    provider: "KHG Graz",
    note: "Catholic student dorm near Uni Graz.",
  },
  {
    id: "dorm-graz-home4students",
    name: "home4students Graz",
    address: "Leechgasse 1",
    postcode: "8010",
    city: "Graz",
    lat: 47.0792,
    lng: 15.4475,
    priceFrom: 320,
    priceTo: 500,
    rooms: 1,
    url: HOME4STUDENTS,
    provider: "home4students",
    note: "Operator residence in the university quarter.",
  },
  {
    id: "dorm-graz-elisabeth",
    name: "Verein Studentenheim Graz",
    address: "Elisabethstraße 85",
    postcode: "8010",
    city: "Graz",
    lat: 47.0658,
    lng: 15.4522,
    priceFrom: 260,
    priceTo: 380,
    rooms: 1,
    url: "https://www.studentenheim-graz.at/",
    provider: "Studentenheim Graz",
    note: "Affordable rooms south of the Mur.",
  },
];

const INNSBRUCK_DORMS: DormRecord[] = [
  {
    id: "dorm-ibk-wist-fuerstenweg",
    name: "WIST Fürstenweg",
    address: "Fürstenweg 174",
    postcode: "6020",
    city: "Innsbruck",
    lat: 47.2522,
    lng: 11.3795,
    priceFrom: 310,
    priceTo: 480,
    rooms: 1,
    url: WIST,
    provider: "WIST Tirol",
    note: "Panorama & Firnberg houses on Fürstenweg.",
  },
  {
    id: "dorm-ibk-karwendel",
    name: "WIST Karwendelheim",
    address: "Höttinger Au 84",
    postcode: "6020",
    city: "Innsbruck",
    lat: 47.2685,
    lng: 11.3722,
    priceFrom: 300,
    priceTo: 460,
    rooms: 1,
    url: WIST,
    provider: "WIST Tirol",
    note: "Hötting area — bus to Innrain campus.",
  },
  {
    id: "dorm-ibk-sieglanger",
    name: "WIST Campus Sieglanger",
    address: "Weingartnerstraße 129",
    postcode: "6020",
    city: "Innsbruck",
    lat: 47.2612,
    lng: 11.4015,
    priceFrom: 320,
    priceTo: 490,
    rooms: 1,
    url: WIST,
    provider: "WIST Tirol",
    note: "Modern campus-style WIST buildings.",
  },
  {
    id: "dorm-ibk-home4students",
    name: "home4students Innsbruck",
    address: "Klosterneubergasse 8",
    postcode: "6020",
    city: "Innsbruck",
    lat: 47.2655,
    lng: 11.3928,
    priceFrom: 340,
    priceTo: 520,
    rooms: 1,
    url: HOME4STUDENTS,
    provider: "home4students",
    note: "Central Innsbruck student housing operator.",
  },
];

const SALZBURG_DORMS: DormRecord[] = [
  {
    id: "dorm-szg-oejab",
    name: "ÖJAB-Haus Salzburg",
    address: "Strubergasse 1",
    postcode: "5020",
    city: "Salzburg",
    lat: 47.8085,
    lng: 13.0412,
    priceFrom: 300,
    priceTo: 470,
    rooms: 1,
    url: OEJAB,
    provider: "ÖJAB",
    note: "Near Salzach — good for PLUS and FH Salzburg.",
  },
  {
    id: "dorm-szg-wist-humboldt",
    name: "WIST Humboldt",
    address: "Egger-Lienz-Gasse 3",
    postcode: "5020",
    city: "Salzburg",
    lat: 47.8022,
    lng: 13.0485,
    priceFrom: 310,
    priceTo: 480,
    rooms: 1,
    url: WIST,
    provider: "WIST Salzburg",
    note: "WIST residence in Elisabeth-Vorstadt.",
  },
  {
    id: "dorm-szg-home4students",
    name: "home4students Salzburg",
    address: "Schallmooser Hauptstraße 56",
    postcode: "5020",
    city: "Salzburg",
    lat: 47.8125,
    lng: 13.0558,
    priceFrom: 350,
    priceTo: 540,
    rooms: 1,
    url: HOME4STUDENTS,
    provider: "home4students",
    note: "Operator listings for Salzburg student rooms.",
  },
];

const KLAGENFURT_DORMS: DormRecord[] = [
  {
    id: "dorm-klu-home4students",
    name: "home4students Klagenfurt",
    address: "Universitätsstraße 65",
    postcode: "9020",
    city: "Klagenfurt",
    lat: 46.6185,
    lng: 14.2682,
    priceFrom: 290,
    priceTo: 450,
    rooms: 1,
    url: HOME4STUDENTS,
    provider: "home4students",
    note: "Near AAU campus.",
  },
  {
    id: "dorm-klu-ktn",
    name: "Kärntner Studierendenheime",
    address: "Bahnhofstraße 8",
    postcode: "9020",
    city: "Klagenfurt",
    lat: 46.6242,
    lng: 14.3105,
    priceFrom: 260,
    priceTo: 400,
    rooms: 1,
    url: "https://jugend.ktn.gv.at/",
    provider: "Land Kärnten",
    note: "Regional student housing directory.",
  },
];

const KREMS_DORMS: DormRecord[] = [
  {
    id: "dorm-krems-oejab",
    name: "ÖJAB-Europazentrum Krems",
    address: "Arbeitergasse 5",
    postcode: "3500",
    city: "Krems",
    lat: 48.4105,
    lng: 15.5985,
    priceFrom: 280,
    priceTo: 420,
    rooms: 1,
    url: OEJAB,
    provider: "ÖJAB",
    note: "Close to IMC and Danube University.",
  },
  {
    id: "dorm-krems-imc",
    name: "IMC Student Housing",
    address: "Piaristengasse 1",
    postcode: "3500",
    city: "Krems",
    lat: 48.4108,
    lng: 15.6012,
    priceFrom: 320,
    priceTo: 500,
    rooms: 1,
    url: "https://www.imc.ac.at/",
    provider: "IMC Krems",
    note: "Check IMC for partner residences and waitlists.",
  },
];

const LEOBEN_DORMS: DormRecord[] = [
  {
    id: "dorm-leoben-montanuni",
    name: "MUVA Montanuniversität Leoben",
    address: "Franz-Josef-Straße 18",
    postcode: "8700",
    city: "Leoben",
    lat: 47.3842,
    lng: 15.0925,
    priceFrom: 250,
    priceTo: 380,
    rooms: 1,
    url: "https://www.unileoben.ac.at/",
    provider: "Montanuniversität",
    note: "University-linked housing options in Leoben.",
  },
  {
    id: "dorm-leoben-oejab",
    name: "ÖJAB Steiermark (Leoben area)",
    address: "Parkstraße 11",
    postcode: "8700",
    city: "Leoben",
    lat: 47.3825,
    lng: 15.0982,
    priceFrom: 240,
    priceTo: 360,
    rooms: 1,
    url: OEJAB,
    provider: "ÖJAB",
    note: "Regional ÖJAB placements — check availability for Leoben.",
  },
];

const ST_POELTEN_DORMS: DormRecord[] = [
  {
    id: "dorm-stp-fh",
    name: "FH St. Pölten Student Housing",
    address: "Campus 1",
    postcode: "3100",
    city: "St. Pölten",
    lat: 48.1897,
    lng: 15.6162,
    priceFrom: 280,
    priceTo: 420,
    rooms: 1,
    url: "https://www.fhstp.ac.at/",
    provider: "FH St. Pölten",
    note: "Campus residences and partner dorms in St. Pölten.",
  },
  {
    id: "dorm-stp-oejab-noe",
    name: "ÖJAB Niederösterreich",
    address: "Herzogenburger Straße 72",
    postcode: "3100",
    city: "St. Pölten",
    lat: 48.1925,
    lng: 15.6215,
    priceFrom: 260,
    priceTo: 390,
    rooms: 1,
    url: OEJAB,
    provider: "ÖJAB",
    note: "NÖ student residences — apply via ÖJAB portal.",
  },
];

const WELS_DORMS: DormRecord[] = [
  {
    id: "dorm-wels-fhoo",
    name: "FH OÖ Wels Campus Housing",
    address: "Stelzhamerstraße 23",
    postcode: "4600",
    city: "Wels",
    lat: 48.1572,
    lng: 14.0418,
    priceFrom: 270,
    priceTo: 410,
    rooms: 1,
    url: "https://www.fh-ooe.at/",
    provider: "FH OÖ",
    note: "FH campus and nearby Wels student rooms.",
  },
];

export const DORMS_BY_CITY: Record<string, DormRecord[]> = {
  vienna: VIENNA_DORMS,
  graz: GRAZ_DORMS,
  innsbruck: INNSBRUCK_DORMS,
  salzburg: SALZBURG_DORMS,
  klagenfurt: KLAGENFURT_DORMS,
  krems: KREMS_DORMS,
  leoben: LEOBEN_DORMS,
  "st-poelten": ST_POELTEN_DORMS,
  wels: WELS_DORMS,
};

export const DORMS_SOURCE_URLS: Record<string, string> = {
  linz: "https://www.jku.at/campus/wohnen/studierendenheime/",
  vienna: OEJAB,
  graz: "https://www.uni-graz.at/de/studieren/beratung-service/wohnen/",
  innsbruck: WIST,
  salzburg: OEJAB,
  klagenfurt: HOME4STUDENTS,
  krems: OEJAB,
  leoben: "https://www.unileoben.ac.at/",
  "st-poelten": "https://www.fhstp.ac.at/",
  wels: "https://www.fh-ooe.at/",
};

export function getCatalogDorms(cityId: string): DormRecord[] {
  return DORMS_BY_CITY[cityId] ?? [];
}

export function getDormsSourceUrl(cityId: string): string {
  return (
    DORMS_SOURCE_URLS[cityId] ??
    "https://www.studium.at/studieren/wohnen/studierendenheime"
  );
}

export function cityIdForDorm(dorm: DormRecord): string {
  const map: Record<string, string> = {
    Linz: "linz",
    Wien: "vienna",
    Graz: "graz",
    Innsbruck: "innsbruck",
    Salzburg: "salzburg",
    Klagenfurt: "klagenfurt",
    Krems: "krems",
    Leoben: "leoben",
    "St. Pölten": "st-poelten",
    Wels: "wels",
  };
  return map[dorm.city] ?? "linz";
}

export function findCatalogDorm(id: string): DormRecord | undefined {
  for (const dorms of Object.values(DORMS_BY_CITY)) {
    const hit = dorms.find((d) => d.id === id);
    if (hit) return hit;
  }
  return undefined;
}
