import { JKU_CAMPUS_POLYGON } from "./jku-campus-polygon";
import type { University } from "./universities";

export const UNIVERSITY_CATALOG: University[] = [
  // Linz
  {
    id: "jku",
    name: "Johannes Kepler University",
    shortName: "JKU",
    cityId: "linz",
    status: "available",
    address: "Altenberger Straße 69, 4040 Linz",
    lat: 48.3384,
    lng: 14.3212,
    campusPolygon: JKU_CAMPUS_POLYGON,
    blurb: "Linz — apartments, WGs and dorms around campus",
  },
  {
    id: "ufg-linz",
    name: "University of Arts Linz",
    shortName: "Kunstuni",
    cityId: "linz",
    status: "available",
    address: "Hauptplatz 8, 4020 Linz",
    lat: 48.3059,
    lng: 14.2865,
    blurb: "Linz housing map centered on Hauptplatz campus",
  },
  {
    id: "bruckneruni",
    name: "Anton Bruckner Private University",
    shortName: "Bruckneruni",
    cityId: "linz",
    status: "available",
    address: "Alice-Strasse 1, 4020 Linz",
    lat: 48.2915,
    lng: 14.2918,
    blurb: "Linz map with commute to Bruckner campus",
  },
  {
    id: "fh-oo-linz",
    name: "FH OÖ Campus Linz",
    shortName: "FH OÖ",
    cityId: "linz",
    status: "available",
    address: "Campus Linz, 4020 Linz",
    lat: 48.2795,
    lng: 14.2895,
    blurb: "Applied sciences campus in Linz",
  },
  // Vienna
  {
    id: "uni-wien",
    name: "University of Vienna",
    shortName: "Uni Wien",
    cityId: "vienna",
    status: "available",
    address: "Universitätsring 1, 1010 Wien",
    lat: 48.2132,
    lng: 16.3601,
    blurb: "Vienna student housing around the main campus",
  },
  {
    id: "tu-wien",
    name: "TU Wien",
    shortName: "TU Wien",
    cityId: "vienna",
    status: "available",
    address: "Karlsplatz 13, 1040 Wien",
    lat: 48.1986,
    lng: 16.3699,
    blurb: "Flats and WGs near TU Wien",
  },
  {
    id: "wu",
    name: "WU Vienna",
    shortName: "WU",
    cityId: "vienna",
    status: "available",
    address: "Welthandelsplatz 1, 1020 Wien",
    lat: 48.214,
    lng: 16.4085,
    blurb: "Housing near WU Prater campus",
  },
  {
    id: "boku",
    name: "University of Natural Resources and Life Sciences",
    shortName: "BOKU",
    cityId: "vienna",
    status: "available",
    address: "Gregor-Mendel-Straße 33, 1180 Wien",
    lat: 48.2392,
    lng: 16.3347,
    blurb: "Rentals near BOKU Muthgasse",
  },
  {
    id: "meduni-wien",
    name: "Medical University of Vienna",
    shortName: "MedUni Wien",
    cityId: "vienna",
    status: "available",
    address: "Spitalgasse 23, 1090 Wien",
    lat: 48.2208,
    lng: 16.355,
    blurb: "Housing near MedUni and AKH",
  },
  {
    id: "fh-technikum-wien",
    name: "FH Technikum Wien",
    shortName: "FH Technikum",
    cityId: "vienna",
    status: "available",
    address: "Höchstädtplatz 6, 1200 Wien",
    lat: 48.2397,
    lng: 16.375,
    blurb: "WGs and flats near FH Technikum",
  },
  // Graz
  {
    id: "uni-graz",
    name: "University of Graz",
    shortName: "Uni Graz",
    cityId: "graz",
    status: "available",
    address: "Universitätsplatz 3, 8010 Graz",
    lat: 47.0781,
    lng: 15.4505,
    blurb: "Graz housing near the historic campus",
  },
  {
    id: "tu-graz",
    name: "TU Graz",
    shortName: "TU Graz",
    cityId: "graz",
    status: "available",
    address: "Rechbauerstraße 12, 8010 Graz",
    lat: 47.0697,
    lng: 15.451,
    blurb: "Flats and WGs around TU Graz",
  },
  {
    id: "meduni-graz",
    name: "Medical University of Graz",
    shortName: "MedUni Graz",
    cityId: "graz",
    status: "available",
    address: "Neue Stiftingtalstraße 6, 8010 Graz",
    lat: 47.0831,
    lng: 15.4686,
    blurb: "Housing near MedUni campus",
  },
  {
    id: "fh-joanneum",
    name: "FH Joanneum",
    shortName: "FH Joanneum",
    cityId: "graz",
    status: "available",
    address: "Alte Poststraße 149, 8020 Graz",
    lat: 47.0589,
    lng: 15.4612,
    blurb: "Applied sciences housing in Graz",
  },
  // Innsbruck
  {
    id: "uni-innsbruck",
    name: "University of Innsbruck",
    shortName: "Uni Innsbruck",
    cityId: "innsbruck",
    status: "available",
    address: "Innrain 52, 6020 Innsbruck",
    lat: 47.264,
    lng: 11.385,
    blurb: "Innsbruck student housing near Innrain",
  },
  {
    id: "mci-innsbruck",
    name: "MCI Management Center Innsbruck",
    shortName: "MCI",
    cityId: "innsbruck",
    status: "available",
    address: "Universitätsstraße 15, 6020 Innsbruck",
    lat: 47.2625,
    lng: 11.3948,
    blurb: "Flats and WGs near MCI",
  },
  {
    id: "fh-kufstein",
    name: "FH Kufstein Tirol",
    shortName: "FH Kufstein",
    cityId: "innsbruck",
    status: "available",
    address: "Andreas Hofer-Straße 7, 6020 Innsbruck",
    lat: 47.2598,
    lng: 11.4012,
    blurb: "Innsbruck branch — use city map for Tirol housing",
  },
  // Salzburg
  {
    id: "uni-salzburg",
    name: "Paris Lodron University Salzburg",
    shortName: "PLUS",
    cityId: "salzburg",
    status: "available",
    address: "Kapitelgasse 4-6, 5020 Salzburg",
    lat: 47.798,
    lng: 13.047,
    blurb: "Salzburg housing near old town campus",
  },
  {
    id: "fh-salzburg",
    name: "FH Salzburg",
    shortName: "FH Salzburg",
    cityId: "salzburg",
    status: "available",
    address: "Urstein Süd 1, 5412 Puch bei Hallein",
    lat: 47.7233,
    lng: 13.0867,
    blurb: "Housing for FH Salzburg Urstein campus",
  },
  // Klagenfurt
  {
    id: "aau",
    name: "Alpen-Adria-Universität Klagenfurt",
    shortName: "AAU",
    cityId: "klagenfurt",
    status: "available",
    address: "Universitätsstraße 65-67, 9020 Klagenfurt",
    lat: 46.6167,
    lng: 14.2653,
    blurb: "Klagenfurt rentals near AAU",
  },
  // Leoben
  {
    id: "montanuni",
    name: "Montanuniversität Leoben",
    shortName: "MUL",
    cityId: "leoben",
    status: "available",
    address: "Franz-Josef-Straße 18, 8700 Leoben",
    lat: 47.3842,
    lng: 15.0925,
    blurb: "Leoben student housing near campus",
  },
  // St. Pölten
  {
    id: "fh-st-poelten",
    name: "FH St. Pölten",
    shortName: "FH St. Pölten",
    cityId: "st-poelten",
    status: "available",
    address: "Campus 1, 3100 St. Pölten",
    lat: 48.1897,
    lng: 15.6162,
    blurb: "Housing for FH St. Pölten students",
  },
  // Wels
  {
    id: "fh-oo-wels",
    name: "FH OÖ Campus Wels",
    shortName: "FH Wels",
    cityId: "wels",
    status: "available",
    address: "Stelzhamerstraße 23, 4600 Wels",
    lat: 48.1572,
    lng: 14.0418,
    blurb: "Wels campus and city rentals",
  },
  // Krems
  {
    id: "imc-krems",
    name: "IMC University of Applied Sciences Krems",
    shortName: "IMC Krems",
    cityId: "krems",
    status: "available",
    address: "Piaristengasse 1, 3500 Krems",
    lat: 48.4108,
    lng: 15.6012,
    blurb: "Krems housing near IMC",
  },
  {
    id: "danube-uni-krems",
    name: "Danube University Krems",
    shortName: "DUK",
    cityId: "krems",
    status: "available",
    address: "Dr.-Karl-Dorrek-Straße 30, 3500 Krems",
    lat: 48.4242,
    lng: 15.6217,
    blurb: "Rentals for Danube University students",
  },
];
